name: CI/CD to EC2

on:
  push:
    branches: ["test1"] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-app ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-app

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app

      - name: Generate .env file
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Upload docker-compose.yml and .env to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: |
            docker-compose.yml
            .env
          target: "/home/ubuntu/PR2/"
          overwrite: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/PR2
            if ! command -v docker-compose &> /dev/null; then
              sudo apt update
              sudo apt install -y docker-compose
            fi

            if [ ! -f .env ]; then
              echo "ERROR: .env no encontrado"
              exit 1
            fi

            sudo docker-compose --env-file .env down --rmi all --volumes --remove-orphans || true
            sudo docker-compose --env-file .env pull
            sudo docker-compose --env-file .env up -d

 
